#!/bin/bash
MASTER=$1
DOMAIN=$2

# Tailscale connection on master
ssh root@$MASTER -oStrictHostKeyChecking=no /bin/bash << EOF
yum -y install epel-release
yum install -y yum-utils
yum -y install firewalld
systemctl enable --now firewalld
EOF

# PREPARATION
sudo yum install -y ansible git pwgen

# BASIS
# Get playbook
git clone https://github.com/spantaleev/matrix-docker-ansible-deploy.git ~/matrix-docker-ansible-deploy
mkdir ~/matrix-docker-ansible-deploy/inventory/host_vars/matrix1.$DOMAIN
cp ~/matrix-docker-ansible-deploy/examples/vars.yml ~/matrix-docker-ansible-deploy/inventory/host_vars/matrix1.$DOMAIN/vars.yml
# Set domain
sed -i 's/YOUR_BARE_DOMAIN_NAME_HERE/'$DOMAIN'/' ~/matrix-docker-ansible-deploy/inventory/host_vars/matrix1.$DOMAIN/vars.yml
# Set homeserver secret
sed -i -e "s/matrix_homeserver_generic_secret_key: ''/matrix_homeserver_generic_secret_key: '$(pwgen -s 64 1)'/" ~/matrix-docker-ansible-deploy/inventory/host_vars/matrix1.$DOMAIN/vars.yml
# Set lets encrypt email
sed -i "s/matrix_ssl_lets_encrypt_support_email: ''/matrix_ssl_lets_encrypt_support_email: 'webmaster@$DOMAIN'/" ~/matrix-docker-ansible-deploy/inventory/host_vars/matrix1.$DOMAIN/vars.yml
# Set postgres password
sed -i -e "s/matrix_postgres_connection_password: ''/matrix_postgres_connection_password: '$(pwgen -s 64 1)'/" ~/matrix-docker-ansible-deploy/inventory/host_vars/matrix1.$DOMAIN/vars.yml

cp ~/matrix-docker-ansible-deploy/examples/hosts ~/matrix-docker-ansible-deploy/inventory/hosts
# set server domain
sed -i 's/matrix.<your-domain>/matrix1.'$DOMAIN'/' ~/matrix-docker-ansible-deploy/inventory/hosts
# set server IP
sed -i "s/<your-server's external IP address>/$MASTER/" ~/matrix-docker-ansible-deploy/inventory/hosts

# ACTIVATE
#install + start
ansible-playbook -i ~/matrix-docker-ansible-deploy/inventory/hosts ~/matrix-docker-ansible-deploy/setup.yml --tags=setup-all,start
